### ISSUE TITLE
Migrate from "dnx" to "dotnet cli"

### ISSUE THREAD

**Issue by cwe1ss** [c3-ls/ServiceFabric-Http#18]
the master branch now uses "dotnet cli" for everything:
- the build script `.\build.ps1` has been changed to build everything with "dotnet cli" instead of "dnvm/dnu"
- the build script now also produces the service fabric package for the sample app. Since the sample app now also uses "dotnet cli" based applications, the Visual Studio "Publish" dialog no longer works (it does not yet support "dotnet cli"). I will write some documentation for this.

**Comment by zoalasaurusrawr** [comment]
Excellent, when do you sleep? Lol. 

I can work on documentation for publishing to the fabric without visual studio.

**Comment by cwe1ss** [comment]
it's my current pet project! :) it's a nice and small project, so it's a great place for playing with dotnet cli, asp.net core, ...! 

Here are some details about how everything works now with dotnet cli in this project:

the samples use the StatelessHost-project - refer to [the documentation](https://github.com/c3-ls/ServiceFabric-Http/wiki/Stateless-ASP.NET-Core-Host) for further details. This means that all ServiceManifest.xml files have been modified.

`build.ps1` starts the [psake](https://github.com/psake/psake) based build process. The build script contains the following steps:
- init: validate parameters
- clean: empty/create "artifacts" folder
- dotnetInstall: installs the latest ".NET Core SDK" (dotnet cli) if it is not yet installed (I need this for the AppVeyor integration)
- dotnetRestore: runs `dotnet restore` on all projects specified in the global.json file
- dotnetBuild: runs `dotnet build` on all projects. AFAIK there's not yet a way to build the whole solution so it just loops through every folder
- dotnetTest: just a placeholder in case I ever find the time to write some tests :-)
- packageNuget: not required for running the samples. I need this for publishing the nuget packages to nuget. It runs `dotnet pack`
- **packageServiceFabric**: That's the important one! It creates the folder structure required by Service Fabric to do the deployment. (application folder which contains ApplicationManifest.xml, a folder for each service which contains the ServiceManifest.xml and the application in a "Code" folder)
  - it looks up the service fabric application (GatewaySample in this case) to get all referenced services (HttpGateway, HttpService in this case). 
  - For every service, it runs `dotnet publish` to move the application to the `Code` folder in the service output folder
  - It's important that the folder name (e.g `Code`) and the `CodePackage` name in ServiceManifest.xml are the same!
  - It copies everything from the service's `PackageRoot` to the output folder of the service (this copies the ServiceManifest.xml)
  - it copies all necessary stuff from the service fabric application project into the output folder. (including the deploy-script and the publish profiles)
  - It appends the build number in all ServiceManifest.xml files and in the ApplicationManifest.xml - this allows for continuous integration/continuous delivery. if the build script is started locally, the build number suffix is "local-<timestamp>". A CI system should overwrite this.
  - The necessary scripts are in `build-helpers.ps1`

This would be the powershell script to build and deploy to your local cluster:

``` powershell
.\build.ps1

cd .\artifacts\GatewaySample\

. .\Scripts\Deploy-FabricApplication.ps1 `
        -ApplicationPackagePath .\ApplicationPackage\ `
        -PublishProfileFile .\PublishProfiles\Local.xml `
        -OverwriteBehavior Always
```

Note the dot and space at the beginning of the last line. See [this post](http://stackoverflow.com/questions/35711540/how-do-i-deploy-service-fabric-application-from-vsts-release-pipeline) for details about why this is required.

It would be great, if you could try this and verify that it works. If you want to enhance this description and create a Wiki page, I would gladly accept that :)

**Comment by zoalasaurusrawr** [comment]
Getting one exception during build, I can't entirely tell if this is due to breaking changes in the lib, or if I've missed something small.

Compiling C3.ServiceFabric.AspNetCore.StatelessHost for .NETFramework,Version=v4.5.1
C:\Program Files\dotnet\bin\dotnet.exe compile-csc @C:\users\wmccullough\Documents\ServiceFabric-Http\src\C3.ServiceFabr
ic.AspNetCore.StatelessHost\obj\Release\net451\dotnet-compile.rsp returned Exit Code 1
C:\users\wmccullough\Documents\ServiceFabric-Http\src\C3.ServiceFabric.AspNetCore.StatelessHost\src\C3.ServiceFabric.Asp
NetCore.StatelessHost\AspNetCoreService.cs(2,28): error CS0234: The type or namespace name 'Server' does not exist in th
e namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
C:\users\wmccullough\Documents\ServiceFabric-Http\src\C3.ServiceFabric.AspNetCore.StatelessHost\src\C3.ServiceFabric.Asp
NetCore.StatelessHost\ServiceFabricWebHostBuilder.cs(79,42): error CS0246: The type or namespace name 'IServerFactory' c
ould not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    2 Error(s)

**Comment by cwe1ss** [comment]
I just switched back to a different aspnet feed which contains the RC2 bits ("aspnetrelease"). However, I also get an error on dotnet restore. I created an issue in the aspnet/home repo - we'll  see what they say...

**Comment by cwe1ss** [comment]
Btw - do you get your error in visual studio or when you execute build.ps1 ?

**Comment by zoalasaurusrawr** [comment]
I got that when building using the build.ps1 script. Sorry for the slow response, real life intervened, lol.

**Comment by zoalasaurusrawr** [comment]
I pulled latest and that seemed to help that issue. Using build.ps1 now results in this:

An item with the same key has already been added. Key: Microsoft.DotNet.ProjectModel.ProjectContextBuilder+LibraryKey
Error: 4/20/2016 9:59:20 AM:
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Exec: Error executing command  dotnet build $_.Di
  rectory -c $BuildConfiguration --version-suffix $BuildNumber .

I've been working through it this morning trying to understand the new build system and what could cause this. The lack of documentation for the dotnet cli is a bit frustrating.

**Comment by cwe1ss** [comment]
I now fixed your initial error - this was due to a breaking change in aspnet/hosting. There will be another breaking change in the next days which they have already committed but is not yet on their myget-feed. I also moved to their "aspnetcirelease" feed (which is a bit more unstable than the "aspnetrelease" feed) to get the previous "libuv" problem fixed.

the build now succeeded on AppVeyor.

your other problem ("An item with the same key...") is a bug in "dotnet cli". can you try it again with the latest version?

Let's hope that all of this will be stable in a few weeks...

**Comment by zoalasaurusrawr** [comment]
I'm hoping for the same thing. It seems that we may be inching towards an official RC2 public build from Microsoft. I'll update the cli and giver it a go!

Thanks again man!

**Comment by zoalasaurusrawr** [comment]
I noticed I'm still getting the error with the updated CLI. Curious, is there a specific procedure for updating the CLI tools? I grabbed the RC2 for my system (x64), from here:

https://github.com/dotnet/cli#installers-and-binaries

Everything installed properly, but still getting that error. I noticed that the error was reported as resolved in the /cli project with Microsoft, but latest seems to be giving me grief still.

**Comment by cwe1ss** [comment]
hmm. I also updated today (1.0.0-rc2-002439) and it works for me. You could try to delete your nuget package cache (c:\users\your-name.nuget\packages) - maybe something got mixed up due to the switches between the different aspnet-feeds.

**Comment by zoalasaurusrawr** [comment]
That didn't do it, but I suspect we are in the realm of that type of issue. I'm going to grab the binaries and manually update my dotnet folder.

Thanks for the assistance, I'm documenting the minor kinks of the CLI so that I can create a go-to page for these specific issues. I recognize they aren't attributed to the project, but the fast moving target that is the dotnet cli.

**Comment by zoalasaurusrawr** [comment]
I think I know what is going on.

When I install the latest CLR with dnvm upgrade -u. It goes to CLR version 20221. When I open the solution, it says that the solution relies upon build 20222. I feel like I may be missing something, lol. dnvm upgrade -u should pull down build 20222 right?

EDIT: Shouldn't the upgrade to dotnet cli invalidate the need for the dnx?

**Comment by cwe1ss** [comment]
I moved back to 20221 which is the latest on the unstable "aspnetvnext" feed - see latest commit on master.

all dnx-related stuff will go away completely with dotnet cli, yes.

**Comment by zoalasaurusrawr** [comment]
Cool, thank you. At this point I'm not sure if the feedback is helping or not, lol.

I'll pull latest and keep working with that.

**Comment by cwe1ss** [comment]
I created a wiki page for the build/deployment process: https://github.com/c3-ls/ServiceFabric-Http/wiki/Build-&-CI
